
export const genres = {
    "ACTION":[
        {
            id:"act1",
            title:"Die Hard",
            rating:"7.6",
            image:"assets/DieHard.jpeg"
        },
        {
            id:"act2",
            title:"The Dark",
            rating:"8",
            image:"assets/DarkKnight.jpg"
        },
        {
            id:"act3",
            title:"Mad Max",
            rating:"8",
            image:"assets/MadMax.jpg"
        },
        {
            id:"act4",
            title:"The Matrix",
            rating:"8",
            image:"assets/matrix.jpg"
        },
        {
            id:"act5",
            title:"John Wick",
            rating:"8",
            image:"assets/JohnWick.jpg"
        },
        {
            id:"act6",
            title:"Impossible",
            rating:"8",
            image:"assets/MI.jpeg"
        },
        {
            id:"act7",
            title:"Justice ",
            rating:"8",
            image:"assets/JusticeLeague.jpg"
        }
    ],
    "SCI-FI":[
        {
            id:"sci1",
            title:"Blade Runner",
            rating:"7.6",
            image:"assets/BladeRunner.jpg"
        },
        {
            id:"sci2",
            title:"2001",
            rating:"8",
            image:"assets/2001.jpg"
        },
        {
            id:"sci3",
            title:"E.T.",
            rating:"8",
            image:"assets/ET.jpeg"
        },
        {
            id:"sci4",
            title:"Inception",
            rating:"8",
            image:"assets/inception.jpg"
        },
        {
            id:"sci5",
            title:"Alien",
            rating:"8",
            image:"assets/alien.jpg"
        },
        {
            id:"sci6",
            title:"Terminator",
            rating:"8",
            image:"assets/terminator.jpg"
        },
        {
            id:"sci7",
            title:"Interstellar",
            rating:"8",
            image:"assets/interstellar.jpg"
        },
    ],
    "THRILLER":[
        {
            id:"thi1",
            title:"psycho",
            rating:"7.6",
            image:"assets/psycho.jpeg"
        },
        {
            id:"thi2",
            title:"The Silence",
            rating:"8",
            image:"assets/lambs.jpg"
        },
        {
            id:"thi3",
            title:"Se7en",
            rating:"7.6",
            image:"assets/seven.jpg"
        },
        {
            id:"thi4",
            title:"Gone Girl",
            rating:"7.6",
            image:"assets/GoneGirl.jpg"
        },
        {
            id:"thi5",
            title:"The Sense",
            rating:"7.6",
            image:"assets/SixthSense.png"
        },
        {
            id:"thi6",
            title:"Scream",
            rating:"7.6",
            image:"assets/scream.jpg"
        },
        {
            id:"thi7",
            title:"plane",
            rating:"7.6",
            image:"assets/plane.png"
        },
    ],
    "HORROR":[
        {
            id:"hor1",
            title:"The Shining",
            rating:"7.6",
            image:"assets/shining.jpeg"
        },
        {
            id:"hor2",
            title:"The Exorcist",
            rating:"7.6",
            image:"assets/exorcist.jpeg"
        },
        {
            id:"hor3",
            title:"Halloween",
            rating:"7.6",
            image:"assets/halloween.jpg"
        },
        {
            id:"hor4",
            title:"Get Out",
            rating:"7.6",
            image:"assets/GetOut.jpg"
        },
        {
            id:"hor5",
            title:"Wrong Turn",
            rating:"7.6",
            image:"assets/Wrongturn.jpg"
        },
        {
            id:"hor6",
            title:"IT",
            rating:"7.6",
            image:"assets/IT.jpeg"
        },
        {
            id:"hor7",
            title:"Living Dead",
            rating:"7.6",
            image:"assets/NOTLD.jpg"
        }
    ],
    "ANIME":[
        {
            id:"ani1",
            title:"Your Name",
            rating:"7.6",
            image:"assets/yourname.jpg"
        },
        {
            id:"ani2",
            title:"Suzume",
            rating:"8",
            image:"assets/suzume.jpg"
        },
        {
            id:"ani3",
            title:"Zero",
            rating:"8",
            image:"assets/jjk.jpg"
        },
        {
            id:"ani4",
            title:"Spirited Away",
            rating:"8",
            image:"assets/SpiritedAway.jpg"
        },
        {
            id:"ani5",
            title:"Kung Panda",
            rating:"8",
            image:"assets/KungFuPanda.jpeg"
        },
        {
            id:"ani6",
            title:"Princess Mono",
            rating:"8",
            image:"assets/PrincessMononoke.jpg"
        },
        {
            id:"ani7",
            title:"Coco",
            rating:"8",
            image:"assets/Coco.jpeg"
        },
    ],
}